services:
  ui:
    build: ./ui
    volumes:
      - shared-data:/app/user_uploads
    ports:
      - "8501:8501"
    networks:
      - ins-chat-network

  api:
    build: ./api_ai
    volumes:
      - shared-data:/app/user_uploads
    ports:
      - "3000:3000"
    networks:
      - ins-chat-network
    depends_on:
      - ui

volumes:
  shared-data:

networks:
  ins-chat-network:
    driver: bridge