services:
  ui:
    build: ./ui
    ports:
      - "8501:8501"
    networks:
      - ins-chat-network

  api:
    build: ./api_ai
    ports:
      - "3000:3000"
    networks:
      - ins-chat-network
    depends_on:
      - ui

networks:
  ins-chat-network:
    driver: bridge